MONGO:
  ADDRESS: '192.168.48.3'
  PORT: 27077
  USERNAME: 'root'
  PASSWORD: '123456'

REDIS:
  HOST: '192.168.48.2'
  PORT: 6399

AUTH:
  IDENTITY:
    - dev
    - prod
    - antx
    - runit
  SALT: '913059'

DEVICE:
  PASS
