MONGO:
  ADDRESS: '127.0.0.1'
  PORT: 27017
  USERNAME: 'root'
  PASSWORD: '123456'

REDIS:
  HOST: '127.0.0.1'
  PORT: 6379

AUTH:
  IDENTITY:
    - dev
    - prod
    - antx
    - runit
  SALT: '913059'

DEVICE:
  PASS
