MONGO:
  ADDRESS: '127.0.0.1'
  PORT: 27017
#  USERNAME: 'root'
#  PASSWORD: '123456'

REDIS:
  HOST: '127.0.0.1'
#  PORT: 57878
  PORT: 6379
#  PASSWORD: runit@redis

AUTH:
  IDENTITY:
    - dev
    - prod
    - antx
    - runit
  SALT: '913059'

DEVICE:
  PASS
