# 使用python镜像自定义我们的镜像
FROM continuumio/miniconda3 AS build

RUN conda update conda -y \
    # 更改中科大源
    && echo "channels:" > ~/.condarc \
    && echo " - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/" >> ~/.condarc \
    && echo " - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/" >> ~/.condarc \
    && echo " - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/" >> ~/.condarc \
    && echo "ssl_verify: true" >> ~/.condarc \
    # 忽略 ttyname failed: Inappropriate ioctl for device 错误
    && sed -i -e 's/mesg n .*true/tty -s \&\& mesg n/g' ~/.profile \
    && cat ~/.condarc \
  && conda env list

# Update conda
RUN conda update -n base -c defaults conda

RUN conda create -n runit python=3.8
#RUN #echo "source activate env" > ~/.bashrc

# Init conda
RUN conda init bash
#RUN conda activate runit
ENV PATH /opt/conda/envs/runit/bin:$PATH

SHELL ["conda", "run", "-n", "runit", "/bin/bash", "-c"]

# 时区同步
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#创建/app目录
RUN mkdir /app

#将项目文件内的requirements.txt拷贝到/app
COPY ./requirements.txt /app
#COPY ./setup.py /app
COPY ./app /app

#使用国内163源
#ADD sources.list /etc/apt

#切换到/app目录
WORKDIR /app

#使用豆瓣源https://pypi.douban.com/simple安装项目的python依赖
#RUN python3 -m pip install --upgrade pip && pip3 install -r requirements.txt --trusted-host https://pypi.douban.com/simple -i https://pypi.douban.com/simple

RUN conda install --yes --file requirements.txt

FROM build AS builder

#将内部的8019端口暴露出去
EXPOSE 8019

ENV PYTHONPATH "${PYTHONPATH}:/app:/app/api:/app/utils"

#使用uvicorn启动应用，IP为0.0.0.0，端口为8019（这里的端口是8019，那么EXPOSE暴露的端口也必须是这个）
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8019","--reload"]

